export const chatsListe = [
	{
		"id": "1",
		"visibility": "Visible au refuge",
		"name": "Mia",
		"color": "noir et blanc",
        "age": " 5 ans",
		"sexe":"Femelle",	
		"pictures" : "/imgChat/mia.jpg",
		"description": ["Mia est une femelle de 5 ans.",<br key="1"/>,
		 "Elle fait partie de la même portée que Jude.",<br key="2"/>,
		 " C'est une chatte également très gentille et en demande d'attention. Elle est énergique et bavarde !        "]},
		
		{"id": "2",
		"visibility": "Visible au refuge",
		"name": "jude",
		"color": "blanc et marron",
        "age": "5 ans",
		"sexe":"Mâle",
		"pictures" : "/imgChat/jude.jpg",
		"description": ["Jude est un fmâle de 5 ans.	",<br key="3"/>,
		 "C'est un gentil chat qui a l'habitude de vivre avec d'autres chats en appartement.",<br key="4"/>,
		 " il est bavard et apprécie le contact des séances câlins "]	},

	{"id": "2",
	"visibility": "Visible au refuge",
	"name": "odin",
	"color": "noir et blanc",
	"age": "5 ans",
	"sexe":"Mâle",
	"pictures" : "/imgChat/odin.jpg",
	"description": ["Odin est un mâle de 5 ans, de la même fratrie que Jude.",<br key="5"/>,
	 "Il est très gentil, câlin et bavard.",<br key="6"/>,
	 " Il a l'habitude de vivre avec d'autres chats en appartement mais sera très heureux s'il a accès à un extérieur       "]
}]