export const chatsListe = [
	{
		"id": "1",
		"visibility": "Visible au refuge",
		"name": "Mia",
		"color": "noir et blanc",
        "age": " 5 ans",
		"sexe":"Femelle",	
		"pictures" : "/imgChat/mia.jpg",
		"description": ["Mia est une femelle de 5 ans.",<br key="1"/>,
		 "Elle fait partie de la même portée que Jude.",<br key="2"/>,
		 " C'est une chatte également très gentille et en demande d'attention. Elle est énergique et bavarde !        "]},
		
		{"id": "2",
		"visibility": "Visible au refuge",
		"name": "jude",
		"color": "blanc et marron",
        "age": "5 ans",
		"sexe":"Mâle",
		"pictures" : "/imgChat/jude.jpg",
		"description": ["Jude est un fmâle de 5 ans.	",<br key="3"/>,
		 "C'est un gentil chat qui a l'habitude de vivre avec d'autres chats en appartement.",<br key="4"/>,
		 " il est bavard et apprécie le contact des séances câlins "]	},

	{"id": "3",
	"visibility": "Visible au refuge",
	"name": "odin",
	"color": "noir et blanc",
	"age": "5 ans",
	"sexe":"Mâle",
	"pictures" : "/imgChat/odin.jpg",
	"description": ["Odin est un mâle de 5 ans, de la même fratrie que Jude.",<br key="5"/>,
	 "Il est très gentil, câlin et bavard.",<br key="6"/>,
	 " Il a l'habitude de vivre avec d'autres chats en appartement mais sera très heureux s'il a accès à un extérieur       "]
},
{"id": "4",
"visibility": "Visible au refuge",
"name": "Hades",
"color": "noir ",
"age": "15 ans",
"sexe":"Mâle",
"pictures" : "/imgChat/hades.jpg",
"description": ["Hadès est un mâle de 15 ans est arrivé au refuge suite à un abandon. ",<br key="5"/>,
 "C'est un chat bavard, sociable,  gentil, très câlin et en demande de contact. Il adore la présence humaine. ",<br key="6"/>,
 "Malgré son âge avancé, il est actif et en bonne santé ! "]
},
{"id": "5",
"visibility": "Visible au refuge",
"name": "stella",
"color": "noir ",
"age": "2 ans",
"sexe":"Femelle",
"pictures" : "/imgChat/stella.jpg",
"description": ["Stella est une jeune chatte de 2 ans qui est arrivée au refuge suite à un sauvetage.  ",<br key="5"/>,
 "Elle est craintive mais pas agressive.  Elle a été habituée à la présence humaine mais peu au contact.  ",<br key="6"/>,
 "Elle aura besoin d'un foyer qui lui laissera le temps de prendre confiance en elle! "]
}
]