export const chatsListe = [
  {
    id: "1",
    visibility: "Visible au refuge",
    name: "Mia",
    color: "noir et blanc",
    age: " 5 ans",
    sexe: "Femelle",
    pictures: "/adopt-un-chat/imgChat/mia.jpg",
    description: [
      "Mia est une femelle de 5 ans.",
      <br key="1" />,
      "Elle fait partie de la même portée que Jude.",
      <br key="2" />,
      " C'est une chatte également très gentille et en demande d'attention. Elle est énergique et bavarde !        ",
    ],
  },

  {
    id: "2",
    visibility: "Visible au refuge",
    name: "jude",
    color: "blanc et marron",
    age: "5 ans",
    sexe: "Mâle",
    pictures: "/adopt-un-chat/imgChat/jude.jpg",
    description: [
      "Jude est un fmâle de 5 ans.	",
      <br key="3" />,
      "C'est un gentil chat qui a l'habitude de vivre avec d'autres chats en appartement.",
      <br key="4" />,
      " il est bavard et apprécie le contact des séances câlins ",
    ],
  },

  {
    id: "3",
    visibility: "Visible au refuge",
    name: "odin",
    color: "noir et blanc",
    age: "5 ans",
    sexe: "Mâle",
    pictures: "/adopt-un-chat/imgChat/odin.jpg",
    description: [
      "Odin est un mâle de 5 ans, de la même fratrie que Jude.",
      <br key="5" />,
      "Il est très gentil, câlin et bavard.",
      <br key="6" />,
      " Il a l'habitude de vivre avec d'autres chats en appartement mais sera très heureux s'il a accès à un extérieur       ",
    ],
  },
  {
    id: "4",
    visibility: "Visible au refuge",
    name: "Hades",
    color: "noir ",
    age: "15 ans",
    sexe: "Mâle",
    pictures: "/adopt-un-chat/imgChat/hades.jpg",
    description: [
      "Hadès est un mâle de 15 ans est arrivé au refuge suite à un abandon. ",
      <br key="5" />,
      "C'est un chat bavard, sociable,  gentil, très câlin et en demande de contact. Il adore la présence humaine. ",
      <br key="6" />,
      "Malgré son âge avancé, il est actif et en bonne santé ! ",
    ],
  },
  {
    id: "5",
    visibility: "Visible au refuge",
    name: "stella",
    color: "noir ",
    age: "2 ans",
    sexe: "Femelle",
    pictures: "/adopt-un-chat/imgChat/stella.jpg",
    description: [
      "Stella est une jeune chatte de 2 ans qui est arrivée au refuge suite à un sauvetage.  ",
      <br key="5" />,
      "Elle est craintive mais pas agressive.  Elle a été habituée à la présence humaine mais peu au contact.  ",
      <br key="6" />,
      "Elle aura besoin d'un foyer qui lui laissera le temps de prendre confiance en elle! ",
    ],
  }, 
  {id: "6",
  visibility: "Visible au refuge",
  name: "Browie",
  color: "noir et blanc",
  age: "5 ans",
  sexe: "Femelle",
  pictures: "/adopt-un-chat/imgChat/browie.jpg",
  description:[
    "Bowie est une femelle de 5 ans. ",
    <br key="5" />,
    "C'est une chatte très affectueuse qui aura besoin d'un extérieur. "]
},

{id: "7",
visibility: "Visible au refuge",
name: "Minouche",
color: "noir, blanc et marron",
age: "13 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/minouche.jpg",
description:[
  "Minouche j'ai 13 ans.  ",
  <br key="6" />,
  "je suis une gentille chatte calme et j'apprécie énormément les moments d'affection. ", <br key="7" />,
]
},
{id: "8",
visibility: "Visible au refuge",
name: "Ptimi",
color: "gris et blanc",
age: "9 ans",
sexe: "Mâle",
pictures: "/adopt-un-chat/imgChat/ptimi.jpg",
description:[
  "Ptimi est un mâle de 9 ans. C'est un chat très doux, calme et gentil.  ",
  <br key="7" />,
  "Il vient du même foyer que Minouche "]
},
{id: "9",
visibility: "Visible au refuge",
name: "Bagheera",
color: "noir",
age: "9 mois",
sexe: "Mâle",
pictures: "/adopt-un-chat/imgChat/Bagheera.jpg",
description:[
  "Bagheera est un mâle de 9 mois. C'est un chat agréable qui apprécie les caresses et les moments de jeu ",
  <br key="7" />,
  " Nous privilégierons un foyer qui pourra lui offrir un extérieur. "]
},
{id: "10",
visibility: "Visible au refuge",
name: "Baloo",
color: "marron et blanc",
age: "4 ans",
sexe: "Mâle",
pictures: "/adopt-un-chat/imgChat/baloo.jpg",
description:[
  "Baloo est un male de 4 ans. Il est doux et affectueux. Il a l'habitude de vivre en appartement",
  <br key="7" />,
  "Il a l'habitude de vivre en appartement et pourra parfaitement vivre dans un foyer ayant déjà un chat. "]
},
{id: "11",
visibility: "Visible au refuge",
name: "Milou",
color: "Gris",
age: "9 ans",
sexe: "Mâle",
pictures: "/adopt-un-chat/imgChat/milou.jpg",
description:[
  "Milou est un mâle de 9 ans, très affectueux et en demande de contact. C'est un gentil chat, calme, qui a besoin d'un toilettage fréquent pour son pelage long. ",
  <br key="7" />,
  "Il s'entend avec les autres chats"]
},
{id: "12",
visibility: "Visible au refuge",
name: "Bellot",
color: "tigré",
age: "1 an",
sexe: "Mâle",
pictures: "/adopt-un-chat/imgChat/bellot.jpg",
description:[
  "Bellot est un mâle de 1 an. C'est un chat très sympathique et actif. Il apprécie le contact avec les humains, plus qu'avec ses congénères. ",
  <br key="7" />,
  "Nous privilégierons une famille sans autre chat. "]
},
{id: "13",
visibility: "Visible au refuge",
name: "Teddy et Théo",
color: "l'un roux, l'autre noir",
age: "5 mois",
sexe: "Mâle",
pictures: "/adopt-un-chat/imgChat/theotedy.png",
description:[
  "Teddy (roux) et moi Théo (noir) nous sommes deux mâles de 5 mois, un peu timides au début, mais passé ce stade, nous prennons confiance. Teddy est plutôt calme, tandis que Théo adore le jeu. Il faudra un peu de patience pour que nous soyons pleinement à l'aise mais nous acceptons déjà les caresses. Nous privilégierons une double adoption.",]
},
{id: "14",
visibility: "Visible au refuge",
name: "Augustine",
color: "tigré",
age: "5 ans",
sexe: "Femele",
pictures: "/adopt-un-chat/imgChat/augustine.jpg",
description:[
  "Augustine j'ai 5 ans, j'ai été abandonnée devant la porte du refuge, j'ai eu besoin d'un peu de temps pour m'adapter et reprendre confiance en moi. Je suis une chatte bavarde et caline, qui a cependant son petit caractère. Je préfére être sans congénère, l'association va privilégier une famille sans autre animal.",]
},
{id: "15",
visibility: "Visible au refuge",
name: "Gribouille",
color: "noir et blanc",
age: "5 ans",
sexe: "Mâle",
pictures: "/adopt-un-chat/imgChat/gribouille.jpg",
description:[
  "Gribouille j'ai 5 ans. j'ai toujours vécu en appartement. J'ai besoin d'une attention particulière pour mon pelage long qui nécessite du brossage. Je suis un chat très doux et agréable",]
},
{id: "16",
visibility: "Visible au refuge",
name: "Minouche",
color: "tricolore",
age: "13 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/minouchev4.png",
description:[
  "Minouche je suis une gentille chatte de 13 ans. J’apprécie les moments de caresses et j'aime aussi avoir des moments de tranquillité. Un foyer sans autre animal sera privilégié. J'ai toujours vécu en appartement mais j'apprécie un petit extérieur",]
},
{id: "17",
visibility: "Visible au refuge",
name: "Bella",
color: "marron et blanc",
age: "1.5 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/bella.png",
description:[
  "Bella je suis une femelle de 1,5 ans. Je suis arrivée au refuge avec Raphaël. Nous sommes deux chats très attachés et extrêmement gentils. Nous privilégierons une double adoption.",]
},
{id: "18",
visibility: "Visible au refuge",
name: "Raphaël",
color: "gris",
age: "1.5 ans",
sexe: "Male",
pictures: "/adopt-un-chat/imgChat/raph.png",
description:[
  "Raphaël je suis un male de 1,5 ans. Je suis arrivé au refuge avec Bella. Nous sommes deux chats très attachés et extrêmement gentils. Nous privilégierons une double adoption.",]
},
{id: "19",
visibility: "Visible au refuge",
name: "Ulysse",
color: "marron",
age: "8 mois",
sexe: "Male",
pictures: "/adopt-un-chat/imgChat/ulysse.png",
description:[
  "Ulysse je suis un mâle de 8 mois. Je suis un chat en demande de beaucoup d'affectation et extrêmement gentil. j'ai besoin d'un foyer avec une présence pour jouer avec moi et me rassurer",]
},
{id: "20",
visibility: "Visible au refuge",
name: "Birdie",
color: "marron",
age: "1 an",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/birdie.png",
description:[
  "Birdie je suis une femme de 1 an, bavarde, active autant que caline. J'aurai besoin d'un extérieur pour m'épanouir pleinement.",]
},
{id: "21",
visibility: "Visible au refuge",
name: "Sabah",
color: "marron et beige",
age: "2 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/sabah.png",
description:[
  "Sabah je suis une femelle de 2 ans. Je suis une chatte agréable qui sait faire connaître ses besoins et ses envies. J'aurai besoin d'un extérieur et de préférence pour m'épanouir pleinement. Un foyer sans autre animal sera privilégié. ",]
},
{id: "22",
visibility: "Visible au refuge",
name: "Ziggie",
color: "marron",
age: "2 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/ziggie.png",
description:[
  "Ziggie je suis une femelle de 2 ans. Je suis une chatte douce et caline, qui apprécierai un petit bout de jardin. Jeune maman, mes chatons sont également visibles au refuge.",]
},
{id: "23",
visibility: "Visible au refuge",
name: "Noisette",
color: "gris et blanc",
age: "5 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/noisette.png",
description:[
  "Noisette je suis une chatte de 5 ans, d'une douceur rare, je suis arrivée au refuge suite au décès de ma maîtresse. J'ai besoin de reprendre confiance en moi dans un foyer calme et affectueux. J'apprécierai un extérieur.",]
},
{id: "24",
visibility: "Visible au refuge",
name: "Titou",
color: "gris ",
age: "15 ans",
sexe: "Male",
pictures: "/adopt-un-chat/imgChat/titou.png",
description:[
  "Titou je suis une chatte de 15 ans et quelques problème de digestions (intolérances aux croquettes). Venez me rencontrer !",]
},
{id: "25",
visibility: "Visible au refuge",
name: "Baloo",
color: "4 ans",
sexe: "Male",
pictures: "/adopt-un-chat/imgChat/baloo.png",
description:[
  "Baloo je suis un mâle de 4 ans, très affectueux et calme. Je vivais dans une cité du 93 avant d'être recueilli au refuge. J'ai un entropion à un oeil, ce qui veut dire que ma paupière est trop longue et que je n'arrive pas à ouvrir entièrement mon oeil. Cependant, je vois correctement et je vais très bien. J'attends sagement mon nouveau foyer",]
},

{id: "26",
visibility: "Visible au refuge",
name: "Lili",
color: "1.5 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/Lili.jpg",
description:[
  "Lili je suis une chatte de 1,5 ans. Je suis très calme et douce, mais je sais me faire comprendre de mes congénères quand je souhaite être tranquille. Je préférerais être le seul animal de mon futur foyer",
]
},{id: "27",
visibility: "Visible au refuge",
name: "Lucky",
color: "4 mois",
sexe: "Male",
pictures: "/adopt-un-chat/imgChat/Lucky.jpg",
description:[
  "Lucky je suis un jeune male de 4 mois. Je suis une machine à ronrons qui ne demande qu'à jouer et être câliné. J'ai cependant besoin d'un peu d'éducation, car je n'ai pas eu la chance d'avoir ma maman pour m'apprendre les bonnes manières. Je saurais cependant rendre heureuse toute une famille",]
},
{id: "28",
visibility: "Visible au refuge",
name: "Malice",
color: "6 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/Malice.jpg",
description:[
  "Malice je suis une femelle de 6 ans. Mon histoire est un mystère. Cependant, je suis une minette très câline et vive. J'accepte les autres chats et surtout les caresses !",]
},
{id: "29",
visibility: "Visible au refuge",
name: "Marvel",
color: "5 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/Marvel.jpg",
description:[
  "Marvel je suis une femelle de 5 ans. Abandonnée car coupable de trop aimer mon maître, il me faudra une famille sans autre congénère pour que je puisse montrer tout l'amour de mon futur foyer, je peux tout à fait vivre en appartement",]
},
{id: "30",
visibility: "Visible au refuge",
name: "Queency",
color: "3 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/Queency.jpg",
description:[
  "Queency je suis une femelle de 3 ans. Je suis adorable et j'ai besoin de prendre confiance pour être pleinement à l'aise. J'apprécie les caresses et les moments de complicité avec les humains,  je peux tout à fait vivre en appartement",]
},
{id: "31",
visibility: "Visible au refuge",
name: "Shadow",
color: "4 ans",
sexe: "Femelle",
pictures: "/adopt-un-chat/imgChat/Shadow.jpg",
description:[
  "Shadow je suis une femelle de 1 an. Arrivée au refuge avec mes chatons, c'est désormais à mon tour de trouver un foyer pour la vie. Je suis une chatte craintive mais extrêmement douce et caline dès qu'on me donne de l'attention. Je préférerais vivre dans un appartement.",]
},


];
